<?php
// This is a PHP script
?>

<!DOCTYPE html>
<html>
<head>
    <title>Simple HTML Page</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <p>This is a simple HTML page generated by a PHP script.</p>
</body>
</html>
