#pragma once

#include <netdb.h>
#include <sys/socket.h>
#include <cstdio>
#include <algorithm>
#include <cstring>
#include <iostream>
#include <cerrno>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <list>
#include <sstream>
#include <unistd.h>
#include <dirent.h>
#include <map>
#include <fcntl.h>
#include <vector>
#include <fstream>
#include <ctime>
#include <exception>
#include <string>
#include <arpa/inet.h>

#include "../Includes/Data.hpp"
#include "../Includes/Parser.hpp"
#include "../Includes/Server.hpp"
#include "../Includes/ConfData.hpp"
#include "../Includes/Client.hpp"
